vim.g.mapleader = " "
vim.opt.tabstop = 3
vim.opt.softtabstop = 3
vim.opt.shiftwidth = 3
vim.opt.expandtab = true
vim.opt.number = true
vim.opt.cursorline = false
vim.opt.wrap = false
vim.opt.mouse = "a"
vim.opt.guicursor = "n-v-i-c:block-Cursor"
vim.opt.hlsearch = false
